import { validateAnyLocalCareerMapState, type AnyLocalCareerMapState } from "./local-career-map-state";
import type { CareerMapCapabilityDefinition } from "./reviewed-resume-evidence-map-adapter";
export const LOCAL_CAREER_MAP_STORAGE_KEY = "careertwin.local-career-map.v1";
type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem">;
export type LocalCareerMapReadResult = { status: "absent" } | { status: "loaded"; state: AnyLocalCareerMapState } | { status: "incompatible_version"; state: AnyLocalCareerMapState } | { status: "invalid"; message: string } | { status: "storage_unavailable"; message: string };
function storage(given?: StorageLike): StorageLike | undefined { if (given) return given; return typeof window === "undefined" ? undefined : window.localStorage; }
export function readLocalCareerMapState(definitions: readonly CareerMapCapabilityDefinition[], definitionVersion: string, given?: StorageLike): LocalCareerMapReadResult { const target = storage(given); if (!target) return { status: "storage_unavailable", message: "Browser storage is unavailable." }; try { const raw = target.getItem(LOCAL_CAREER_MAP_STORAGE_KEY); if (raw === null) return { status: "absent" }; const parsed = JSON.parse(raw); const validated = validateAnyLocalCareerMapState(parsed, definitions); if (!validated.ok) return { status: "invalid", message: validated.issues[0].message }; const stateVersion = validated.state.schemaVersion === "1.0.0" ? validated.state.definitionVersion : validated.state.schemaVersion === "2.0.0" ? validated.state.versions.capabilityDefinitionVersion : definitionVersion; return stateVersion === definitionVersion ? { status: "loaded", state: validated.state } : { status: "incompatible_version", state: validated.state }; } catch { return { status: "invalid", message: "Saved browser data could not be read." }; } }
export function writeLocalCareerMapState(state: AnyLocalCareerMapState, definitions: readonly CareerMapCapabilityDefinition[], given?: StorageLike): { ok: true } | { ok: false; status: "invalid" | "storage_unavailable"; message: string } { const validated = validateAnyLocalCareerMapState(state, definitions); if (!validated.ok) return { ok: false, status: "invalid", message: validated.issues[0].message }; let serialized: string; try { serialized = JSON.stringify(validated.state); } catch { return { ok: false, status: "invalid", message: "Saved browser data could not be serialized." }; } const target = storage(given); if (!target) return { ok: false, status: "storage_unavailable", message: "Browser storage is unavailable." }; try { target.setItem(LOCAL_CAREER_MAP_STORAGE_KEY, serialized); return { ok: true }; } catch { return { ok: false, status: "storage_unavailable", message: "Browser storage is unavailable." }; } }
export function clearLocalCareerMapState(given?: StorageLike): { ok: true } | { ok: false; message: string } { const target = storage(given); if (!target) return { ok: false, message: "Browser storage is unavailable." }; try { target.removeItem(LOCAL_CAREER_MAP_STORAGE_KEY); return { ok: true }; } catch { return { ok: false, message: "Browser storage is unavailable." }; } }
