import type { ProvisionalEvidenceSignalPolicy, ProvisionalEvidenceSignalRule } from "./provisional-evidence-signal-contract";

export const PROVISIONAL_EVIDENCE_SIGNAL_POLICY_VERSION = "provisional-evidence-signal-policy/1.1.0" as const;
const rule = (value: ProvisionalEvidenceSignalRule) => Object.freeze(value);
const notPerformed = ["\\b(?:planned to|intended to|proposed|would|could)\\b", "\\b(?:required to|must|should|candidate will|role will|responsibilities include|will be responsible for)\\b"];

/** Bounded lexical rules only. This is not a general résumé NLP or capability classifier. */
export const provisionalEvidenceSignalPolicy: ProvisionalEvidenceSignalPolicy = Object.freeze({
  policyVersion: PROVISIONAL_EVIDENCE_SIGNAL_POLICY_VERSION,
  coverage: "bounded_non_exhaustive",
  vocabulary: Object.freeze(["designed_research", "supported_research_delivery", "synthesised_findings", "informed_decision", "coordinated_cross_functional_delivery", "owned_delivery", "redesigned_process", "cross_functional", "hypothetical"] as const),
  rules: Object.freeze([
    rule({ ruleId: "signal/action/designed-research", ruleVersion: "1.1.0", field: "action", token: "designed_research", sourcePattern: "\\b(?:designed|developed)\\s+(?:a\\s+|the\\s+)?(?:research|research study|research programme|research program)\\b", exclusionPatterns: ["\\bsupported\\b", "\\bassisted\\b", ...notPerformed], explanation: "Explicit source language records designing research." }),
    rule({ ruleId: "signal/action/designed-research-method", ruleVersion: "1.1.0", field: "action", token: "designed_research", sourcePattern: "\\b(?:(?:built|created|implemented|established|launched)\\s+(?:a\\s+|an\\s+|the\\s+)?(?:structured\\s+)?(?:(?:research|measurement|evaluation)\\s+(?:framework|methodology|approach)|(?:experiment|test|survey)\\s+design)|developed\\s+(?:a\\s+|an\\s+|the\\s+)?(?:experiment|test|survey)\\s+design)\\b", exclusionPatterns: ["\\bdashboard\\b", "\\breport\\b", "\\bSQL\\b", ...notPerformed], explanation: "Explicit creation language tied to a research, measurement, evaluation, experiment, test, or survey design records research-design work." }),
    rule({ ruleId: "signal/action/supported-research", ruleVersion: "1.1.0", field: "action", token: "supported_research_delivery", sourcePattern: "\\b(?:supported|assisted|contributed to)\\s+(?:the\\s+)?(?:delivery of\\s+)?research\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit participation language records support for research delivery without ownership." }),
    rule({ ruleId: "signal/action/synthesised-findings", ruleVersion: "1.1.0", field: "action", token: "synthesised_findings", sourcePattern: "\\bsynthesi[sz]ed\\s+(?:research\\s+|customer\\s+|study\\s+)?(?:findings|insights|evidence)\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit source language records synthesising findings." }),
    rule({ ruleId: "signal/action/synthesised-recommendations", ruleVersion: "1.1.0", field: "action", token: "synthesised_findings", sourcePattern: "\\b(?:synthesi[sz]ed|translated)\\s+(?:the\\s+)?(?:analysis|findings|evidence|insights)\\s+into\\s+(?:business\\s+|commercial\\s+)?recommendations\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit source language records translating evidence or analysis into recommendations." }),
    rule({ ruleId: "signal/action/combined-sources-insights", ruleVersion: "1.1.0", field: "action", token: "synthesised_findings", sourcePattern: "\\b(?:combined|integrated)\\s+(?:multiple\\s+|several\\s+)?(?:data|evidence)\\s+sources?\\s+to\\s+(?:identify|derive)\\s+(?:findings|insights|recommendations)\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit combination of multiple evidence sources into findings records synthesis." }),
    rule({ ruleId: "signal/outcome/informed-decision", ruleVersion: "1.1.0", field: "outcome", token: "informed_decision", sourcePattern: "\\b(?:to|that|which)\\s+(?:inform(?:ed)?|enabl(?:e|ed)|support(?:ed)?)\\s+(?:a\\s+|the\\s+)?(?:(?:business|commercial|product|customer)\\s+)?(?:decision|decisions|decision-making)\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit causal language connects the evidence to a decision." }),
    rule({ ruleId: "signal/outcome/recommendations-from-evidence", ruleVersion: "1.1.0", field: "outcome", token: "informed_decision", sourcePattern: "\\b(?:synthesi[sz]ed|translated)\\s+(?:the\\s+)?(?:analysis|findings|evidence|insights)\\s+into\\s+(?:business\\s+|commercial\\s+)?recommendations\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit recommendations derived from analysis or evidence record decision-support output." }),
    rule({ ruleId: "signal/action/coordinated-cross-functional", ruleVersion: "1.1.0", field: "action", token: "coordinated_cross_functional_delivery", sourcePattern: "\\b(?:coordinated|drove|led|managed)\\s+(?:a\\s+|the\\s+)?cross[- ]functional\\s+(?:delivery|initiative|project|programme|program|team)\\b", exclusionPatterns: ["\\bsupported\\b", "\\bassisted\\b", ...notPerformed], explanation: "Explicit source language records coordinating cross-functional delivery." }),
    rule({ ruleId: "signal/action/coordinated-delivery-across", ruleVersion: "1.1.0", field: "action", token: "coordinated_cross_functional_delivery", sourcePattern: "\\b(?:coordinated|aligned)\\s+(?:the\\s+)?(?:delivery|stakeholders?)\\s+(?:across|to\\s+deliver\\s+across)\\s+[A-Za-z][^.;]{2,80}\\b", exclusionPatterns: ["\\bsupported\\b", "\\bassisted\\b", ...notPerformed], explanation: "Explicit coordination of delivery across named groups records cross-functional delivery coordination." }),
    rule({ ruleId: "signal/ownership/owned-delivery", ruleVersion: "1.1.0", field: "ownership", token: "owned_delivery", sourcePattern: "\\b(?:owned|drove|led|managed|was responsible for)\\s+(?:a\\s+|the\\s+)?(?:cross[- ]functional\\s+)?(?:delivery|initiative|project|programme|program|team)\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit ownership language records delivery ownership." }),
    rule({ ruleId: "signal/action/redesigned-process", ruleVersion: "1.1.0", field: "action", token: "redesigned_process", sourcePattern: "\\b(?:redesigned|re-engineered|reengineered|overhauled)\\s+(?:a\\s+|the\\s+)?(?:process|workflow|operating process)\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit source language records redesigning a process." }),
    rule({ ruleId: "signal/action/improved-explicit-process", ruleVersion: "1.1.0", field: "action", token: "redesigned_process", sourcePattern: "\\b(?:improved|optimi[sz]ed|streamlined|standardi[sz]ed|transformed|automated)\\s+(?:a\\s+|an\\s+|the\\s+)?(?:recurring\\s+reporting|reporting\\s+(?:process|workflow)|analytics\\s+workflow|measurement\\s+process|governance\\s+process|delivery\\s+process|decision\\s+process|operating\\s+process|workflow|process)\\b", exclusionPatterns: ["\\b(?:revenue|sales|growth)\\b", ...notPerformed], explanation: "Explicit improvement language tied to a named repeatable process or workflow records process improvement." }),
    rule({ ruleId: "signal/action/established-governance-process", ruleVersion: "1.1.0", field: "action", token: "redesigned_process", sourcePattern: "\\bestablished\\s+(?:a\\s+|an\\s+|the\\s+)?(?:reporting\\s+|measurement\\s+|data\\s+)?governance\\s+process\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit establishment of a governance process records process improvement." }),
    rule({ ruleId: "signal/action/scaled-operating-model", ruleVersion: "1.1.0", field: "action", token: "redesigned_process", sourcePattern: "\\bscaled\\s+(?:a\\s+|an\\s+|the\\s+)?repeatable\\s+(?:operating\\s+model|workflow|process)\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit scaling of a repeatable operating model, workflow, or process records process improvement." }),
    rule({ ruleId: "signal/scope/cross-functional", ruleVersion: "1.1.0", field: "scope", token: "cross_functional", sourcePattern: "\\bcross[- ]functional\\b", exclusionPatterns: [...notPerformed], explanation: "The source explicitly states cross-functional scope." }),
    rule({ ruleId: "signal/scope/collaboration-across-groups", ruleVersion: "1.1.0", field: "scope", token: "cross_functional", sourcePattern: "\\b(?:partnered|collaborated|worked)\\s+(?:with|across)\\s+[A-Z][A-Za-z& /-]+?\\s+(?:and|,)\\s+[A-Z][A-Za-z& /-]+", exclusionPatterns: [...notPerformed], explanation: "Explicit collaboration across multiple named groups records cross-functional scope without ownership." }),
    rule({ ruleId: "signal/scope/delivery-across-groups", ruleVersion: "1.1.0", field: "scope", token: "cross_functional", sourcePattern: "\\b(?:delivery|stakeholders?)\\s+across\\s+[A-Za-z][^.;]{2,80}\\b", exclusionPatterns: [...notPerformed], explanation: "Explicit delivery or stakeholder coordination across groups records cross-functional scope." }),
    rule({ ruleId: "signal/context/hypothetical", ruleVersion: "1.0.0", field: "context", token: "hypothetical", sourcePattern: "\\b(?:proposed|would|could|planned to|intended to)\\b", exclusionPatterns: [], explanation: "The source explicitly frames the activity as hypothetical or intended." }),
    rule({ ruleId: "signal/participation/non-owner", ruleVersion: "1.0.0", field: "participation", sourcePattern: "\\b(?:supported|assisted|contributed to|partnered on)\\b", exclusionPatterns: [], explanation: "Participation language is retained as a guard and never promoted to ownership." }),
  ]),
});
