import type { ProvisionalMappingPolicy, ProvisionalMappingRule } from "./provisional-resume-mapping-contract";

export const PROVISIONAL_RESUME_MAPPING_POLICY_VERSION = "provisional-resume-mapping-policy/1.2.0" as const;
const authoredRule = (rule: ProvisionalMappingRule): ProvisionalMappingRule => Object.freeze(rule);

/** Intentionally bounded proof set. Absence of a rule means unsupported, never a guessed match. */
export const provisionalResumeMappingPolicy: ProvisionalMappingPolicy = Object.freeze({
  policyVersion: PROVISIONAL_RESUME_MAPPING_POLICY_VERSION,
  coverage: "bounded_non_exhaustive",
  rules: Object.freeze([
    authoredRule({ ruleId: "research-design/direct/designed-research", ruleVersion: "1.0.0", capabilityId: "research-design", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "designed_research" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records designing research." }),
    authoredRule({ ruleId: "research-design/transferable/supported-research", ruleVersion: "1.0.0", capabilityId: "research-design", relationship: "transferable_signal", requiredSignals: Object.freeze([{ field: "action", value: "supported_research_delivery" }]), excludedSignals: Object.freeze([]), explanation: "The evidence records supporting research delivery without claiming research design ownership." }),
    authoredRule({ ruleId: "insight-synthesis/direct/synthesised-findings", ruleVersion: "1.0.0", capabilityId: "insight-synthesis", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "synthesised_findings" }, { field: "outcome", value: "informed_decision" }]), excludedSignals: Object.freeze([{ field: "action", value: "synthesised_executive_insight" }]), explanation: "The evidence explicitly connects synthesised findings to a decision." }),
    authoredRule({ ruleId: "cross-functional-delivery/direct/coordinated-delivery", ruleVersion: "1.0.0", capabilityId: "cross-functional-delivery", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "coordinated_cross_functional_delivery" }, { field: "ownership", value: "owned_delivery" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records owned cross-functional delivery." }),
    authoredRule({ ruleId: "process-improvement/direct/redesigned-process", ruleVersion: "1.0.0", capabilityId: "process-improvement", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "redesigned_process" }]), excludedSignals: Object.freeze([{ field: "context", value: "hypothetical" }]), explanation: "The evidence explicitly records redesigning an operating process." }),
    authoredRule({ ruleId: "strategic-analysis/direct/performed-strategic-analysis", ruleVersion: "1.0.0", capabilityId: "strategic-analysis", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "performed_strategic_analysis" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records performed strategic analysis." }),
    authoredRule({ ruleId: "insight-synthesis/direct/synthesised-executive-insight", ruleVersion: "1.0.0", capabilityId: "insight-synthesis", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "synthesised_executive_insight" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records synthesising insight for an executive audience." }),
    authoredRule({ ruleId: "analytics-governance/direct/established-analytics-governance", ruleVersion: "1.0.0", capabilityId: "analytics-governance", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "established_analytics_governance" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records establishing analytics governance." }),
    authoredRule({ ruleId: "people-leadership/direct/led-analytics-team", ruleVersion: "1.0.0", capabilityId: "people-leadership", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "led_analytics_team" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records leading an analytics team." }),
    authoredRule({ ruleId: "measurement-design/direct/designed-measurement-framework", ruleVersion: "1.0.0", capabilityId: "measurement-design", relationship: "direct_evidence", requiredSignals: Object.freeze([{ field: "action", value: "designed_measurement_framework" }]), excludedSignals: Object.freeze([]), explanation: "The evidence explicitly records designing a measurement framework or methodology." }),
  ]),
});
