import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildProvisionalCareerMapFromFile } from "../../lib/career-possibility/build-provisional-career-map-from-file";
import { canonicalCapabilityLibrary } from "../../lib/career-possibility/canonical-capability-library";

const text = "EXPERIENCE\n- Designed a research study.\n- Prepared weekly notes.";
const bytes = (type: "pdf" | "docx") => type === "pdf" ? new Uint8Array([0x25,0x50,0x44,0x46,0x2d,1]) : new Uint8Array([0x50,0x4b,0x03,0x04,1]);
const file = (type: "pdf" | "docx") => { const data = bytes(type); return { name: `synthetic.${type}`, type: type === "pdf" ? "application/pdf" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document", size: data.byteLength, arrayBuffer: async () => data.buffer }; };
const run = (type: "pdf" | "docx", stages: string[]) => buildProvisionalCareerMapFromFile({ file: file(type), capabilityDefinitions: canonicalCapabilityLibrary.capabilities, capabilityDefinitionVersion: canonicalCapabilityLibrary.contentVersion, createdAt: "2026-08-04T00:00:00Z", updatedAt: "2026-08-04T00:00:00Z", onStage: (stage) => stages.push(stage), parserDependencies: type === "pdf" ? { extractPdf: async () => text } : { extractDocx: async () => text } });
async function main() {
  for (const type of ["pdf", "docx"] as const) { const stages: string[] = []; const result = await run(type, stages); assert.equal(result.status, "success"); assert.deepEqual(stages, ["reading", "building"]); if (result.status !== "success") throw new Error(); assert.equal(result.state.schemaVersion, "2.0.0"); assert.equal(result.state.source, "provisional_resume"); assert.equal(result.state.mapTrustStatus, "provisional"); assert.equal(result.state.evidence.every((item) => item.reviewStatus === "unreviewed"), true); assert.equal(result.state.mappings.every((item) => item.reviewStatus === "unreviewed" && item.admissionStatus === "auto_admitted"), true); assert.equal(result.state.unresolvedEvidence.length, 1); }
  const unsupported = await buildProvisionalCareerMapFromFile({ file: { name: "cv.txt", type: "text/plain", size: 4, arrayBuffer: async () => new ArrayBuffer(4) }, capabilityDefinitions: canonicalCapabilityLibrary.capabilities, capabilityDefinitionVersion: canonicalCapabilityLibrary.contentVersion, createdAt: "x", updatedAt: "x" }); assert.deepEqual(unsupported, { status: "failure", code: "unsupported_file" });
  const large = await buildProvisionalCareerMapFromFile({ file: { name: "cv.pdf", type: "application/pdf", size: 5 * 1024 * 1024 + 1, arrayBuffer: async () => new ArrayBuffer(0) }, capabilityDefinitions: canonicalCapabilityLibrary.capabilities, capabilityDefinitionVersion: canonicalCapabilityLibrary.contentVersion, createdAt: "x", updatedAt: "x" }); assert.deepEqual(large, { status: "failure", code: "file_too_large" });
  const noMappings = await buildProvisionalCareerMapFromFile({ file: file("pdf"), capabilityDefinitions: canonicalCapabilityLibrary.capabilities, capabilityDefinitionVersion: canonicalCapabilityLibrary.contentVersion, createdAt: "x", updatedAt: "x", parserDependencies: { extractPdf: async () => "EXPERIENCE\n- Prepared weekly notes." } }); assert.deepEqual(noMappings, { status: "failure", code: "no_unambiguous_mappings" });
  const source = readFileSync("lib/career-possibility/build-provisional-career-map-from-file.ts", "utf8"); assert.match(source, /extractLocalResumeFile/); assert.match(source, /buildCareerSourceRevision/); assert.match(source, /buildProvisionalCareerMapFromText/); assert.doesNotMatch(source, /localStorage|writeLocalCareerMapState|fetch\(|supabase|openai|embedding|signal\/action|designed_research/);
  console.log("build provisional career map from file tests passed");
}
main().catch((error) => { process.exitCode = 1; throw error; });
