import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { canonicalCapabilityLibrary } from "../../lib/career-possibility/canonical-capability-library";
import { canonicalCapabilityGovernanceLibrary } from "../../lib/career-possibility/canonical-capability-governance-decisions";
import { GENERIC_ROLE_ARCHETYPE_CONTENT_VERSION, GENERIC_ROLE_ARCHETYPE_SCHEMA_VERSION, projectGenericRoleArchetypeToProfile, representativeGenericRoleArchetypes, representativeGenericRoleProfiles, validateGenericRoleArchetypes, type GenericRoleArchetype } from "../../lib/career-possibility/generic-role-archetype";
import { roleCapabilityProfileById, roleCapabilityProfiles } from "../../lib/career-possibility/fixtures/roleCapabilityProfiles";
import { reconcileRoleCapabilityProfilesWithCanonicalLibrary } from "../../lib/career-possibility/role-capability-registry-reconciliation";

assert.equal(GENERIC_ROLE_ARCHETYPE_SCHEMA_VERSION, "1.0.0"); assert.equal(GENERIC_ROLE_ARCHETYPE_CONTENT_VERSION, "1.1.0");
const valid = validateGenericRoleArchetypes(representativeGenericRoleArchetypes, canonicalCapabilityLibrary); assert.equal(valid.ok, true);
assert.deepEqual(representativeGenericRoleArchetypes.map((item) => item.roleFamilyId), ["analytics-manager", "customer-insights-lead", "marketing-analytics-lead", "data-product-manager", "product-operations-manager", "customer-experience-manager", "account-manager", "business-development-manager", "service-delivery-manager", "finance-business-partner", "fpa-manager", "engineering-manager"]);
const admittedRoleTitles = ["Analytics Manager", "Customer Insights Lead", "Marketing Analytics Lead", "Data Product Manager", "Product Operations Manager", "Customer Experience Manager", "Account Manager", "Business Development Manager", "Service Delivery Manager", "Finance Business Partner", "FP&A Manager", "Engineering Manager"];
const profilesBefore = JSON.stringify(representativeGenericRoleProfiles); const developmentProfilesBefore = JSON.stringify(roleCapabilityProfiles);
assert.equal(representativeGenericRoleProfiles.length, 12); assert.deepEqual(representativeGenericRoleProfiles.map((item) => item.canonicalTitle), admittedRoleTitles);
assert.deepEqual(representativeGenericRoleProfiles.map((item) => item.roleFamilyId), representativeGenericRoleArchetypes.map((item) => item.roleFamilyId));
assert.deepEqual(representativeGenericRoleProfiles.map((item) => item.description), representativeGenericRoleArchetypes.map((item) => item.primaryMandate));
assert.equal(representativeGenericRoleProfiles.every((item) => item.description.trim().length > 0), true);
assert.equal(Object.isFrozen(representativeGenericRoleProfiles), true); assert.equal(JSON.stringify(JSON.parse(profilesBefore)), profilesBefore); assert.deepEqual([...representativeGenericRoleProfiles], [...representativeGenericRoleProfiles]);
const byId = new Map(representativeGenericRoleArchetypes.map((item) => [item.roleFamilyId, item])); const analytics = byId.get("analytics-manager")!; const customer = byId.get("customer-insights-lead")!; const marketing = byId.get("marketing-analytics-lead")!; const product = byId.get("data-product-manager")!;
assert.notEqual(analytics.primaryMandate, customer.primaryMandate); assert.notDeepEqual(analytics.identityDefiningCapabilities.map((x) => x.capabilityId), marketing.identityDefiningCapabilities.map((x) => x.capabilityId)); assert.notDeepEqual(analytics.primaryOwnership, product.primaryOwnership); assert.notDeepEqual(customer.identityDefiningCapabilities.map((x) => x.capabilityId), marketing.identityDefiningCapabilities.map((x) => x.capabilityId));
for (const role of representativeGenericRoleArchetypes) { assert.ok(role.differentiators.length); assert.ok(role.evidenceExpectations.length); assert.equal(Object.isFrozen(role), true); assert.equal(Object.isFrozen(role.identityDefiningCapabilities), true); assert.equal(JSON.stringify(JSON.parse(JSON.stringify(role))), JSON.stringify(role)); assert.deepEqual(projectGenericRoleArchetypeToProfile(role), projectGenericRoleArchetypeToProfile(role)); const projected = roleCapabilityProfileById.get(role.roleFamilyId)!; assert.deepEqual(projected, projectGenericRoleArchetypeToProfile(role)); assert.equal(Object.isFrozen(projected.commonGrowthAreas[0]), true); assert.deepEqual(projected.mustHaveCapabilities.map((x) => x.capabilityId), [...role.identityDefiningCapabilities, ...role.coreEnablers].filter((x) => x.importance === "must").map((x) => x.capabilityId)); }
assert.equal(roleCapabilityProfiles.length, 27); assert.equal(reconcileRoleCapabilityProfilesWithCanonicalLibrary({ profiles: roleCapabilityProfiles, canonicalLibrary: canonicalCapabilityLibrary, governanceLibrary: canonicalCapabilityGovernanceLibrary }).coverage.governanceComplete, true);
assert.equal(JSON.stringify(representativeGenericRoleProfiles), profilesBefore); assert.equal(JSON.stringify(roleCapabilityProfiles), developmentProfilesBefore);
const routeSource = readFileSync("app/career-map/page.tsx", "utf8");
assert.equal(routeSource.includes('roles={representativeGenericRoleProfiles}'), false); assert.equal(routeSource.includes('roles={roleCapabilityProfiles}'), false); assert.equal(routeSource.includes("sourceNotes"), false);
const componentSource = readFileSync("components/career-possibility/TargetRoleCapabilityComparison.tsx", "utf8");
assert.equal(componentSource.includes("{role.canonicalTitle}"), true); assert.equal(componentSource.includes("{role.description}"), true);
assert.equal(/generatedRoleSummary|dayToDayResponsibilities|fitScore|readinessScore|suitability|jobDescription|matchV2/i.test(profilesBefore), false);

const expectIssue = (mutate: (copy: GenericRoleArchetype[]) => void, code: string) => { const copy = structuredClone(representativeGenericRoleArchetypes) as GenericRoleArchetype[]; mutate(copy); const result = validateGenericRoleArchetypes(copy, canonicalCapabilityLibrary); assert.equal(result.ok, false); if (!result.ok) assert.ok(result.issues.some((item) => item.code === code), `${code}: ${result.issues.map((x) => x.code).join(",")}`); };
expectIssue((x) => { Object.assign(x[0], { schemaVersion: "2.0.0" }); }, "unsupported_schema_version"); expectIssue((x) => { Object.assign(x[0], { primaryMandate: "" }); }, "blank_primary_mandate"); expectIssue((x) => { Object.assign(x[0], { primaryOwnership: [] }); }, "missing_primary_ownership"); expectIssue((x) => { (x[0].primaryOwnership as string[]).push(x[0].primaryOwnership[0]); }, "duplicate_primary_ownership"); expectIssue((x) => { Object.assign(x[0], { identityDefiningCapabilities: [] }); }, "missing_identity_capability"); expectIssue((x) => { Object.assign(x[0], { coreEnablers: [] }); }, "missing_core_enabler"); expectIssue((x) => { Object.assign(x[0].coreEnablers[0], { importance: "differentiator" }); }, "incompatible_importance"); expectIssue((x) => { Object.assign(x[0], { differentiators: [] }); }, "missing_differentiator"); expectIssue((x) => { Object.assign(x[0], { primaryMandate: "Own Company A's JD" }); }, "company_or_jd_specific_text"); expectIssue((x) => { (x[0].supportingCapabilities as GenericRoleArchetype["supportingCapabilities"][number][]).push(x[0].identityDefiningCapabilities[0]); }, "duplicate_structural_capability"); expectIssue((x) => { Object.assign(x[0].identityDefiningCapabilities[0], { capabilityId: "analytics-leadership" }); }, "unknown_canonical_capability"); expectIssue((x) => { Object.assign(x[0].identityDefiningCapabilities[0], { capabilityId: "matter-management" }); }, "unknown_canonical_capability"); expectIssue((x) => { Object.assign(x[0].identityDefiningCapabilities[0], { capabilityId: "unknown-id" }); }, "unknown_canonical_capability"); expectIssue((x) => { Object.assign(x[1], { roleFamilyId: x[0].roleFamilyId }); }, "duplicate_role_id"); expectIssue((x) => { Object.assign(x[0].evidenceExpectations[1], { id: x[0].evidenceExpectations[0].id }); }, "duplicate_evidence_expectation_id"); expectIssue((x) => { Object.assign(x[0].identityDefiningCapabilities[0], { label: "Drift" }); }, "canonical_label_mismatch"); expectIssue((x) => { Object.assign(x[0].identityDefiningCapabilities[0], { canonicalFamily: "Drift" }); }, "canonical_family_mismatch");
console.log("generic role archetype tests passed");
