import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { LOCAL_CAREER_MAP_STORAGE_KEY, clearLocalCareerMapState, readLocalCareerMapState, writeLocalCareerMapState } from "../../lib/career-possibility/local-career-map-storage";
import type { LocalCareerMapState } from "../../lib/career-possibility/local-career-map-state";
const definitions = [{ id: "forecasting", label: "Forecasting", family: "Analytics & Insight" }]; const state: LocalCareerMapState = { schemaVersion: "1.0.0", definitionVersion: "defs/1", source: "reviewed_resume", importedAt: "x", updatedAt: "x", capabilities: [{ capabilityId: "forecasting", capabilityLabel: "Forecasting", family: "Analytics & Insight", mappings: [{ mappingId: "m", evidenceId: "e", relationship: "direct_evidence", sourceText: "Evidence", sourceStart: 0, sourceEnd: 8, provisional: true }] }] };
const data = new Map<string,string>([["unrelated", "keep"]]); const storage = { getItem: (k:string) => data.get(k) ?? null, setItem: (k:string,v:string) => { data.set(k,v); }, removeItem: (k:string) => { data.delete(k); } };
assert.deepEqual(readLocalCareerMapState(definitions, "defs/1", storage), { status: "absent" }); assert.deepEqual(writeLocalCareerMapState(state, definitions, storage), { ok: true }); assert.equal(readLocalCareerMapState(definitions, "defs/1", storage).status, "loaded"); assert.equal(readLocalCareerMapState(definitions, "defs/2", storage).status, "incompatible_version"); assert.deepEqual(clearLocalCareerMapState(storage), { ok: true }); assert.equal(data.get("unrelated"), "keep"); data.set(LOCAL_CAREER_MAP_STORAGE_KEY, "{"); assert.equal(readLocalCareerMapState(definitions, "defs/1", storage).status, "invalid"); assert.equal(readLocalCareerMapState(definitions, "defs/1").status, "storage_unavailable");
const workspaceSource = readFileSync("components/career-possibility/LocalCareerMapWorkspace.tsx", "utf8");
const routeSource = readFileSync("app/career-map/page.tsx", "utf8");
assert.match(workspaceSource, /No personal Career Map has been created yet\./);
assert.match(workspaceSource, />Start with your résumé</);
assert.match(workspaceSource, /href="\/"/);
assert.doesNotMatch(workspaceSource, /Your career, replicated\.|Uncover your career map|Example Career Map|Mock data preview|EXAMPLE SIGNAL|Capabilities into future directions/);
assert.match(workspaceSource, /if \(result\.status === "loaded"\)/);
assert.ok(workspaceSource.indexOf('if (result.status === "loaded")') < workspaceSource.indexOf("No personal Career Map has been created yet."));
assert.match(workspaceSource, /window\.addEventListener\("pageshow", refresh\)/);
assert.match(workspaceSource, /window\.addEventListener\("focus", refresh\)/);
assert.match(workspaceSource, /document\.addEventListener\("visibilitychange", visible\)/);
assert.match(workspaceSource, /Upload another CV/);
assert.match(workspaceSource, /replaces this browser-local Career Map/);
assert.doesNotMatch(workspaceSource, /supplement|append|CandidateBaseline|best fit|job readiness|suitability/i);
assert.doesNotMatch(routeSource, /Explore a capability map/);
console.log("local career map storage tests passed");
