import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { canonicalCapabilityLibrary } from "../../lib/career-possibility/canonical-capability-library";
import { bridgeEvidenceToProvisionalSignals, validateProvisionalEvidenceSignalPolicy, validateProvisionalEvidenceSignalRule, validateProvisionalEvidenceSignalUnresolved, validateProvisionalStructuredEvidence } from "../../lib/career-possibility/provisional-evidence-signal-bridge";
import type { ProvisionalEvidenceSignalInput, ProvisionalEvidenceSignalPolicy } from "../../lib/career-possibility/provisional-evidence-signal-contract";
import { PROVISIONAL_EVIDENCE_SIGNAL_POLICY_VERSION, provisionalEvidenceSignalPolicy } from "../../lib/career-possibility/provisional-evidence-signal-policy";
import { mapProvisionalResumeEvidence } from "../../lib/career-possibility/provisional-resume-capability-mapper";
import { provisionalResumeMappingPolicy } from "../../lib/career-possibility/provisional-resume-mapping-policy";

const definitions = canonicalCapabilityLibrary.capabilities;
const definitionVersion = canonicalCapabilityLibrary.contentVersion;
const fixture = (id: string, text: string, offset = 0): ProvisionalEvidenceSignalInput => ({ evidence: { id, employmentRecordId: "employment:synthetic", sourceSpanIds: [`span:${id}`], sourceText: text, reviewStatus: "unreviewed", processingStatus: "source_provided", extractionMethod: "deterministic", warnings: [] }, sourceSpans: [{ id: `span:${id}`, documentId: "document:synthetic", sourceType: "resume_upload", employmentRecordId: "employment:synthetic", startOffset: offset, endOffset: offset + text.length, originalText: text }] });
const bridge = (input: ProvisionalEvidenceSignalInput, policy = provisionalEvidenceSignalPolicy) => bridgeEvidenceToProvisionalSignals(input, policy);
const map = async (result: Awaited<ReturnType<typeof bridge>>) => result.status === "structured" ? mapProvisionalResumeEvidence({ evidence: result.evidence, policy: provisionalResumeMappingPolicy, capabilityDefinitions: definitions, capabilityDefinitionVersion: definitionVersion }) : undefined;

async function main() {
  const direct = await bridge(fixture("research-direct", "Designed a research study for customer discovery."));
  assert.equal(direct.status, "structured"); if (direct.status !== "structured") throw new Error();
  assert.deepEqual(direct.evidence.signals, [{ field: "action", value: "designed_research" }]); assert.equal(direct.evidence.reviewStatus, "unreviewed"); assert.deepEqual(validateProvisionalStructuredEvidence(direct.evidence, provisionalEvidenceSignalPolicy), []);
  const directMapping = await map(direct); assert.equal(directMapping?.status, "auto_admitted"); if (directMapping?.status === "auto_admitted") { assert.equal(directMapping.mapping.capabilityId, "research-design"); assert.equal(directMapping.mapping.relationship, "direct_evidence"); }

  const support = await bridge(fixture("research-support", "Supported the delivery of research interviews.")); assert.equal(support.status, "structured"); if (support.status !== "structured") throw new Error(); assert.deepEqual(support.evidence.signals, [{ field: "action", value: "supported_research_delivery" }]); assert.equal(support.evidence.signals.some((item) => item.field === "ownership"), false);
  const supportMapping = await map(support); assert.equal(supportMapping?.status, "auto_admitted"); if (supportMapping?.status === "auto_admitted") assert.equal(supportMapping.mapping.relationship, "transferable_signal");

  const insight = await bridge(fixture("insight", "Synthesized research findings to inform a decision.")); assert.equal(insight.status, "structured"); if (insight.status !== "structured") throw new Error(); assert.deepEqual(insight.evidence.signals, [{ field: "action", value: "synthesised_findings" }, { field: "outcome", value: "informed_decision" }]); const insightMapping = await map(insight); assert.equal(insightMapping?.status, "auto_admitted");
  const crossFunctional = await bridge(fixture("cross-functional", "Led a cross-functional delivery program.")); assert.equal(crossFunctional.status, "structured"); if (crossFunctional.status !== "structured") throw new Error(); assert.deepEqual(crossFunctional.evidence.signals, [{ field: "action", value: "coordinated_cross_functional_delivery" }, { field: "ownership", value: "owned_delivery" }, { field: "scope", value: "cross_functional" }]); const crossMapping = await map(crossFunctional); assert.equal(crossMapping?.status, "auto_admitted");
  const process = await bridge(fixture("process", "Redesigned the operating process.")); assert.equal(process.status, "structured"); if (process.status !== "structured") throw new Error(); assert.deepEqual(process.evidence.signals, [{ field: "action", value: "redesigned_process" }]); const processMapping = await map(process); assert.equal(processMapping?.status, "auto_admitted");

  const participation = await bridge(fixture("participation", "Assisted the delivery team with documentation.")); assert.equal(participation.status, "unsupported"); if (participation.status === "unsupported") assert.equal(participation.unresolved.reason, "no_authored_signal_rule");
  const activityOnly = await bridge(fixture("activity", "Synthesized research findings for the weekly meeting.")); assert.equal(activityOnly.status, "structured"); if (activityOnly.status === "structured") assert.equal(activityOnly.evidence.signals.some((item) => item.field === "outcome"), false);
  const titleOnly = await bridge(fixture("title", "Senior Research Director")); assert.equal(titleOnly.status, "unsupported");
  const toolOnly = await bridge(fixture("tool", "Tableau, Power BI, SQL")); assert.equal(toolOnly.status, "unsupported");
  const ambiguous = await bridge(fixture("ambiguous", "Designed research and redesigned the operating process.")); assert.equal(ambiguous.status, "unresolved"); if (ambiguous.status === "unresolved") assert.equal(ambiguous.unresolved.reason, "multiple_action_signals");
  const ownershipConflict = await bridge(fixture("ownership-conflict", "Owned delivery and assisted the team.")); assert.equal(ownershipConflict.status, "unresolved"); if (ownershipConflict.status === "unresolved") assert.equal(ownershipConflict.unresolved.reason, "ownership_conflict");
  const hypothetical = await bridge(fixture("hypothetical", "Proposed a redesigned process.")); assert.equal(hypothetical.status, "structured"); if (hypothetical.status === "structured") assert.deepEqual(hypothetical.evidence.signals, [{ field: "context", value: "hypothetical" }]); assert.equal((await map(hypothetical))?.status, "unsupported");

  const unsupported = await bridge(fixture("unsupported", "Prepared weekly notes.")); assert.equal(unsupported.status, "unsupported"); if (unsupported.status === "unsupported") { assert.equal(unsupported.unresolved.reason, "no_authored_signal_rule"); assert.deepEqual(validateProvisionalEvidenceSignalUnresolved(unsupported.unresolved), []); }
  const invalid = await bridge({ evidence: { ...fixture("invalid", "Designed research.").evidence, reviewStatus: "confirmed" }, sourceSpans: fixture("invalid", "Designed research.").sourceSpans }); assert.equal(invalid.status, "unresolved"); if (invalid.status === "unresolved") assert.equal(invalid.unresolved.reason, "invalid_evidence");
  const duplicatePolicy: ProvisionalEvidenceSignalPolicy = { ...provisionalEvidenceSignalPolicy, rules: [provisionalEvidenceSignalPolicy.rules[0], provisionalEvidenceSignalPolicy.rules[0]] }; assert.equal(validateProvisionalEvidenceSignalPolicy(duplicatePolicy).some((item) => item.code === "duplicate_rule_id"), true); const invalidPolicy = await bridge(fixture("invalid-policy", "Designed research."), duplicatePolicy); assert.equal(invalidPolicy.status, "unresolved"); if (invalidPolicy.status === "unresolved") assert.equal(invalidPolicy.unresolved.reason, "invalid_signal_policy");
  assert.equal(validateProvisionalEvidenceSignalRule({ ...provisionalEvidenceSignalPolicy.rules[0], explanation: "" }, provisionalEvidenceSignalPolicy.vocabulary).some((item) => item.code === "missing_explanation"), true);
  assert.equal(validateProvisionalEvidenceSignalRule({ ...provisionalEvidenceSignalPolicy.rules[0], token: "unknown" as never }, provisionalEvidenceSignalPolicy.vocabulary).some((item) => item.code === "unknown_signal_token"), true);

  const repeated = await bridge(fixture("research-direct", "Designed a research study for customer discovery.")); assert.deepEqual(repeated, direct);
  const differentId = await bridge(fixture("research-direct-2", "Designed a research study for customer discovery.", 100)); assert.equal(differentId.status, "structured"); if (differentId.status === "structured") assert.notEqual(differentId.evidence.signalIdentity, direct.evidence.signalIdentity);
  const changedPolicy = await bridge(fixture("research-direct", "Designed a research study for customer discovery."), { ...provisionalEvidenceSignalPolicy, policyVersion: "provisional-evidence-signal-policy/1.0.1" }); assert.equal(changedPolicy.status, "structured"); if (changedPolicy.status === "structured") assert.notEqual(changedPolicy.evidence.signalIdentity, direct.evidence.signalIdentity);
  assert.equal(PROVISIONAL_EVIDENCE_SIGNAL_POLICY_VERSION, provisionalEvidenceSignalPolicy.policyVersion); assert.equal(provisionalEvidenceSignalPolicy.coverage, "bounded_non_exhaustive"); assert.equal(provisionalEvidenceSignalPolicy.vocabulary.length, 9); assert.equal(provisionalEvidenceSignalPolicy.rules.length, 10);
  assert.equal("capabilityId" in direct.evidence, false); assert.equal("mappingId" in direct.evidence, false);
  const source = ["provisional-evidence-signal-contract.ts", "provisional-evidence-signal-policy.ts", "provisional-evidence-signal-bridge.ts"].map((name) => readFileSync(new URL(`../../lib/career-possibility/${name}`, import.meta.url), "utf8")).join("\n"); assert.doesNotMatch(source, /\bfetch\s*\(|supabase|localStorage|indexedDB|openai|anthropic|embedding|fuzzy|react|next\//i);

  const row = (name: string, result: Awaited<ReturnType<typeof bridge>>, mapped: Awaited<ReturnType<typeof map>>) => ({ fixture: name, rule: result.status === "structured" ? result.evidence.matchedSignalRuleIds.join(", ") : result.unresolved.matchedSignalRuleIds.join(", "), signals: result.status === "structured" ? result.evidence.signals.map((item) => `${item.field}:${item.value}`).join(", ") : "", bridge: result.status, mapping: mapped?.status ?? "excluded", capability: mapped?.status === "auto_admitted" ? mapped.mapping.capabilityId : "", relationship: mapped?.status === "auto_admitted" ? mapped.mapping.relationship : "" });
  console.table([row("research design direct", direct, directMapping), row("research support transferable", support, supportMapping), row("insight synthesis", insight, insightMapping), row("cross-functional delivery", crossFunctional, crossMapping), row("process improvement", process, processMapping), row("ambiguous evidence", ambiguous, undefined), row("unsupported evidence", unsupported, undefined)]);
  console.log("provisional evidence signal bridge tests passed");
}

main().catch((error) => { process.exitCode = 1; throw error; });
