import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const root = readFileSync("app/page.tsx", "utf8"); const upload = readFileSync("components/career-possibility/RootCvUploadWorkspace.tsx", "utf8"); const explorer = readFileSync("components/career-possibility/CapabilityExplorer.tsx", "utf8"); const result = readFileSync("components/career-possibility/LocalCareerMapWorkspace.tsx", "utf8"); const personal = readFileSync("components/career-possibility/PersonalCapabilityExplorer.tsx", "utf8");
assert.match(root, /Your career, replicated\./); assert.match(root, /See how your experience connects to capabilities/); assert.match(root, /Interactive example · not your data/); assert.match(root, /<CapabilityExplorer result=\{mockCareerPossibility\} variant="hero"/); assert.match(explorer, /variant\?: "full" \| "hero"/);
assert.match(root, /<RootCvUploadWorkspace/); assert.match(upload, /Upload your CV/); assert.equal((upload.match(/"Upload CV"/g) ?? []).length, 1); assert.match(upload, /type="file"/); assert.match(upload, /accept="\.pdf,\.docx/); assert.match(upload, /void selected\(file\)/); assert.match(upload, /Reading your CV\.\.\./); assert.match(upload, /Building your Career Map\.\.\./); assert.match(upload, /aria-live="polite"/); assert.match(upload, /disabled=\{busy\}/); assert.match(upload, /writeLocalCareerMapState/); assert.match(upload, /router\.push\("\/career-map"\)/); assert.match(upload, /Uploading another CV will replace the Career Map stored in this browser\./);
assert.doesNotMatch(`${root}\n${upload}`, /textarea|paste-text|Build my Career Map|stepper|Frontend prototype|No backend connection yet|CV attached|supplement|append|Needs your input|Missing experience/i);
assert.match(result, /Generated from your CV/); assert.match(result, /Provisional until you review or correct the evidence/); assert.match(result, /No personal Career Map has been created yet\./); assert.match(result, />Start with your résumé</); assert.doesNotMatch(result, /Your career, replicated|Example Career Map|Mock data preview|EXAMPLE SIGNAL/); assert.match(result, /TargetRoleCapabilityComparison/); assert.match(personal, /CV-derived · unreviewed/); assert.match(personal, /Direct evidence/); assert.match(personal, /Transferable signal/);
assert.equal((`${root}\n${upload}\n${result}`.match(/careertwin\.local-career-map\.v1/g) ?? []).length, 0);
console.log("root direct upload tests passed");
