"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { CareerMapCapabilityDefinition } from "@/lib/career-possibility/reviewed-resume-evidence-map-adapter";
import { clearLocalCareerMapState, readLocalCareerMapState, type LocalCareerMapReadResult } from "@/lib/career-possibility/local-career-map-storage";

export function LocalCareerMapWorkspace({ definitions, definitionVersion, fallback }: { definitions: readonly CareerMapCapabilityDefinition[]; definitionVersion: string; fallback: React.ReactNode }) {
  const [result, setResult] = useState<LocalCareerMapReadResult | null>(null);
  useEffect(() => { const id = window.setTimeout(() => setResult(readLocalCareerMapState(definitions, definitionVersion)), 0); return () => window.clearTimeout(id); }, [definitions, definitionVersion]);
  function clear() { if (!window.confirm("Clear imported résumé evidence stored in this browser?")) return; const cleared = clearLocalCareerMapState(); if (cleared.ok) setResult({ status: "absent" }); }
  if (!result) return <div className="py-16 text-center text-sm text-slate-500">Loading browser-local Career Map…</div>;
  if (result.status === "loaded") return <section className="py-7"><div className="rounded-2xl border border-teal-300/20 bg-teal-300/[0.05] p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">Imported from reviewed résumé evidence</p><h1 className="mt-2 text-3xl font-semibold">Your provisional capability map</h1><p className="mt-2 text-sm text-slate-400">Stored only in this browser. These mappings reflect your reviewed evidence, not external verification.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/career-map/resume-intake" className="min-h-11 rounded-lg border border-cyan-300/25 px-4 py-3 text-sm text-cyan-200">Start a new résumé review</Link><button type="button" onClick={clear} className="min-h-11 rounded-lg border border-red-300/20 px-4 text-sm text-red-200">Clear imported résumé evidence</button></div></div><div className="mt-6 grid gap-4 md:grid-cols-2">{result.state.capabilities.map((capability) => <article key={capability.capabilityId} className="rounded-2xl border border-white/10 bg-[#08111d] p-5"><p className="text-xs uppercase tracking-[0.16em] text-cyan-300">{capability.family}</p><h2 className="mt-2 text-xl font-semibold">{capability.capabilityLabel}</h2><p className="mt-1 text-xs text-amber-200">Provisional · {capability.mappings.length} reviewed mapping{capability.mappings.length === 1 ? "" : "s"}</p><ul className="mt-4 grid gap-3">{capability.mappings.map((mapping) => <li key={mapping.mappingId} className="rounded-xl border border-white/[0.07] p-3"><p className="text-sm leading-6 text-slate-300">{mapping.sourceText}</p><p className="mt-2 text-xs text-slate-500">{mapping.relationship.replace("_", " ")}</p></li>)}</ul></article>)}</div></section>;
  if (result.status === "incompatible_version") return <StateNotice title="Saved Career Map needs review" message="Your saved Career Map was created with an older capability definition version. Review the résumé mappings again before applying them." clear={clear} />;
  if (result.status === "invalid") return <StateNotice title="Saved browser data could not be read" message={result.message} clear={clear} />;
  if (result.status === "storage_unavailable") return <StateNotice title="Browser storage is unavailable" message={result.message} />;
  return <><div className="rounded-xl border border-cyan-100/10 bg-white/[0.025] p-4 text-sm text-slate-400"><p>No résumé evidence has been applied to this browser.</p><Link href="/career-map/resume-intake" className="mt-3 inline-block min-h-11 rounded-lg border border-cyan-300/25 px-4 py-3 text-cyan-200">Import résumé evidence</Link></div>{fallback}</>;
}
function StateNotice({ title, message, clear }: { title: string; message: string; clear?: () => void }) { return <section className="my-8 rounded-2xl border border-amber-300/20 bg-amber-300/[0.05] p-5"><h1 className="text-xl font-semibold text-amber-100">{title}</h1><p className="mt-2 text-sm text-amber-100/70">{message}</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/career-map/resume-intake" className="min-h-11 rounded-lg border border-cyan-300/25 px-4 py-3 text-sm text-cyan-200">Review résumé again</Link>{clear && <button type="button" onClick={clear} className="min-h-11 rounded-lg border border-red-300/20 px-4 text-sm text-red-200">Clear saved Career Map</button>}</div></section>; }
