"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { CareerMapCapabilityDefinition } from "@/lib/career-possibility/reviewed-resume-evidence-map-adapter";
import { clearLocalCareerMapState, readLocalCareerMapState, type LocalCareerMapReadResult } from "@/lib/career-possibility/local-career-map-storage";
import { buildPersonalCareerMapPresentation } from "@/lib/career-possibility/local-career-map-presentation-adapter";
import { PersonalCapabilityExplorer } from "./PersonalCapabilityExplorer";
import { TargetRoleCapabilityComparison } from "./TargetRoleCapabilityComparison";
import type { RoleCapabilityProfile } from "@/lib/career-possibility/role-capability-library";
import type { CanonicalCapabilityLibrary } from "@/lib/career-possibility/canonical-capability-library";
import type { CanonicalCapabilityGovernanceLibrary } from "@/lib/career-possibility/canonical-capability-governance-decisions";

export function LocalCareerMapWorkspace({ definitions, definitionVersion, roles, canonicalLibrary, governance }: { definitions: readonly CareerMapCapabilityDefinition[]; definitionVersion: string; roles: readonly RoleCapabilityProfile[]; canonicalLibrary: CanonicalCapabilityLibrary; governance: CanonicalCapabilityGovernanceLibrary }) {
  const [result, setResult] = useState<LocalCareerMapReadResult | null>(null); const refresh = useCallback(() => setResult(readLocalCareerMapState(definitions, definitionVersion)), [definitions, definitionVersion]);
  useEffect(() => { const id = window.setTimeout(refresh, 0); const visible = () => { if (document.visibilityState === "visible") refresh(); }; window.addEventListener("focus", refresh); window.addEventListener("pageshow", refresh); window.addEventListener("storage", refresh); document.addEventListener("visibilitychange", visible); return () => { window.clearTimeout(id); window.removeEventListener("focus", refresh); window.removeEventListener("pageshow", refresh); window.removeEventListener("storage", refresh); document.removeEventListener("visibilitychange", visible); }; }, [refresh]);
  function clear() { if (!window.confirm("Clear the Career Map stored in this browser?")) return; if (clearLocalCareerMapState().ok) setResult({ status: "absent" }); }
  if (!result) return <div className="py-16 text-center text-sm text-cyan-50/45">Loading browser-local Career Map…</div>;
  if (result.status === "loaded") { const personal = buildPersonalCareerMapPresentation({ localState: result.state, canonicalDefinitions: definitions }); if (!personal.ok) return <StateNotice title="Saved browser data could not be read" message={personal.issues[0].message} clear={clear} />; const provisional = result.state.schemaVersion === "2.0.0"; return <section className="py-7"><div className="rounded-2xl bg-cyan-300/[0.055] p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">{provisional ? "Generated from your CV" : "Imported from reviewed CV evidence"}</p><h1 className="mt-2 text-3xl font-semibold">Your Career Map</h1><p className="mt-2 text-sm text-cyan-50/60">{provisional ? "Provisional until you review or correct the evidence. Stored only in this browser." : "Reviewed evidence remains browser-local and is not externally verified."}</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/" className="min-h-11 rounded-lg border border-cyan-300/25 px-4 py-3 text-sm text-cyan-200">Upload another CV</Link><button type="button" onClick={clear} className="min-h-11 rounded-lg border border-red-300/20 px-4 text-sm text-red-200">Clear Career Map</button></div><p className="mt-3 text-xs text-cyan-50/40">Uploading another CV replaces this browser-local Career Map.</p></div><PersonalCapabilityExplorer presentation={personal.presentation} /><TargetRoleCapabilityComparison state={result.state} roles={roles} canonicalLibrary={canonicalLibrary} governance={governance} definitionVersion={definitionVersion} /></section>; }
  if (result.status === "incompatible_version") return <StateNotice title="Saved Career Map needs review" message="Your saved Career Map uses an older capability definition version." clear={clear} />;
  if (result.status === "invalid") return <StateNotice title="Saved browser data could not be read" message={result.message} clear={clear} />;
  if (result.status === "storage_unavailable") return <StateNotice title="Browser storage is unavailable" message={result.message} />;
  return <section className="mx-auto my-16 max-w-xl py-10 text-center sm:my-24"><h1 className="text-2xl font-semibold sm:text-3xl">No personal Career Map has been created yet.</h1><Link href="/" className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 transition hover:bg-cyan-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-200">Start with your résumé</Link></section>;
}
function StateNotice({ title, message, clear }: { title: string; message: string; clear?: () => void }) { return <section className="my-8 rounded-2xl bg-amber-300/[0.06] p-5"><h1 className="text-xl font-semibold text-amber-100">{title}</h1><p className="mt-2 text-sm text-amber-100/70">{message}</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/" className="min-h-11 rounded-lg border border-cyan-300/25 px-4 py-3 text-sm text-cyan-200">Upload your CV</Link>{clear && <button type="button" onClick={clear} className="min-h-11 rounded-lg border border-red-300/20 px-4 text-sm text-red-200">Clear saved Career Map</button>}</div></section>; }
