"use client";
import { useEffect, useRef, useState } from "react";
import type { PersonalCareerMapPresentation } from "@/lib/career-possibility/local-career-map-presentation-adapter";

export function PersonalCapabilityExplorer({ presentation }: { presentation: PersonalCareerMapPresentation }) {
  const [expandedId, setExpandedId] = useState<string | null>(null); const provisional = presentation.mapTrustStatus === "provisional"; const triggers = useRef(new Map<string, HTMLButtonElement>()); const detailHeading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (expandedId) detailHeading.current?.focus(); }, [expandedId]);
  function close(id: string) { setExpandedId(null); window.setTimeout(() => triggers.current.get(id)?.focus(), 0); }
  return <section id="personal-explorer-heading" tabIndex={-1} className="mt-4 focus-visible:outline-none" aria-label="Career Map capabilities"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{presentation.capabilities.map((capability) => { const open = expandedId === capability.id; const contentId = `personal-capability-${capability.id}`; return <article key={capability.id} className={`rounded-2xl bg-[#07111d] transition ${open ? "sm:col-span-2 xl:col-span-3" : "hover:bg-[#091625]"}`}><button ref={(node) => { if (node) triggers.current.set(capability.id, node); else triggers.current.delete(capability.id); }} type="button" aria-expanded={open} aria-controls={contentId} onClick={() => open ? close(capability.id) : setExpandedId(capability.id)} className="flex min-h-36 w-full items-start justify-between gap-4 rounded-2xl p-5 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200"><span><span className="block text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-300">{capability.family}</span><span className="mt-2 block text-xl font-semibold text-slate-50">{capability.label}</span><span className="mt-3 block text-sm text-cyan-50/55">{capability.evidence.length} supporting {capability.evidence.length === 1 ? "example" : "examples"}</span></span><span aria-hidden="true" className="mt-1 text-lg text-cyan-200/70">{open ? "−" : "+"}</span></button>{open && <div id={contentId} className="border-t border-white/[0.07] px-5 pb-5 pt-4"><div className="flex items-start justify-between gap-4"><div><h2 ref={detailHeading} tabIndex={-1} className="text-lg font-semibold focus-visible:outline-none">{capability.label} details</h2><p className="mt-1 text-xs text-cyan-50/45">{provisional ? "Based on unreviewed CV evidence" : "Based on reviewed CV evidence"}</p></div><button type="button" onClick={() => close(capability.id)} className="min-h-11 rounded-lg px-3 text-sm text-cyan-200 hover:bg-white/[0.05] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200">Close details</button></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{capability.evidence.map((evidence) => <section key={evidence.id} className="rounded-xl bg-black/15 p-4"><p className="text-xs font-medium text-amber-100/80">{evidence.relationship === "direct_evidence" ? "Direct evidence" : "Transferable signal"} · {provisional ? "Not reviewed" : "Reviewed"}</p><p className="mt-2 text-sm leading-6 text-slate-300">{evidence.text}</p><p className="mt-2 text-[10px] text-cyan-50/35">Source span {evidence.sourceStart}–{evidence.sourceEnd}</p></section>)}</div></div>}</article>; })}</div></section>;
}
